create or replace view vertex_fact_fund_account as

select cct.fund_account_id,
               
  COALESCE(loan_purchase_num, 0) as loan_purchase_num,
  COALESCE(loan_purchase_total, 0) as loan_purchase_total,
  COALESCE(loan_purchase_modification_num, 0) as loan_purchase_modification_num,
  COALESCE(loan_purchase_modification_total, 0) as loan_purchase_modification_total,
  COALESCE(loan_purchase_auto_num, 0) as loan_purchase_auto_num,
  COALESCE(loan_purchase_auto_total, 0) as loan_purchase_auto_total,
  COALESCE(loan_expired_num, 0) as loan_expired_num,
  COALESCE(loan_expired_total, 0) as loan_expired_total,
  COALESCE(loan_expired_modification_num, 0) as loan_expired_modification_num,
  COALESCE(loan_expired_modification_total, 0) as loan_expired_modification_total,
  COALESCE(loan_refund_num, 0) as loan_refund_num,
  COALESCE(loan_refund_total, 0) as loan_refund_total,
  COALESCE(loan_refund_modification_num, 0) as loan_refund_modification_num,
  COALESCE(loan_refund_modification_total, 0) as loan_refund_modification_total,
  COALESCE(gift_purchase_num, 0) as gift_purchase_num,
  COALESCE(gift_purchase_total, 0) as gift_purchase_total,
  COALESCE(gift_purchase_modification_num, 0) as gift_purchase_modification_num,
  COALESCE(gift_purchase_modification_total, 0) as gift_purchase_modification_total,
  COALESCE(gift_redemption_num, 0) as gift_redemption_num,
  COALESCE(gift_redemption_total, 0) as gift_redemption_total,
  COALESCE(gift_expiration_num, 0) as gift_expiration_num,
  COALESCE(gift_expiration_total, 0) as gift_expiration_total,
  COALESCE(gift_expiration_modification_num, 0) as gift_expiration_modification_num,
  COALESCE(gift_expiration_modification_total, 0) as gift_expiration_modification_total,
  COALESCE(gift_expiration_donation_num, 0) as gift_expiration_donation_num,
  COALESCE(gift_expiration_donation_total, 0) as gift_expiration_donation_total,
  COALESCE(gift_expiration_donation_modification_num, 0) as gift_expiration_donation_modification_num,
  COALESCE(gift_expiration_donation_modification_total, 0) as gift_expiration_donation_modification_total,
  COALESCE(withdrawal_num, 0) as withdrawal_num,
  COALESCE(withdrawal_total, 0) as withdrawal_total,
  COALESCE(withdrawal_modification_num, 0) as withdrawal_modification_num,
  COALESCE(withdrawal_modification_total, 0) as withdrawal_modification_total,
  COALESCE(donation_num, 0) as donation_num,
  COALESCE(donation_total, 0) as donation_total,
  COALESCE(donation_modification_num, 0) as donation_modification_num,
  COALESCE(donation_modification_total, 0) as donation_modification_total,
  COALESCE(donation_auto_num, 0) as donation_auto_num,
  COALESCE(donation_auto_total, 0) as donation_auto_total,
  COALESCE(loan_repayment_num, 0) as loan_repayment_num,
  COALESCE(loan_repayment_total, 0) as loan_repayment_total,
  COALESCE(loan_repayment_currency_loss_num, 0) as loan_repayment_currency_loss_num,
  COALESCE(loan_repayment_currency_loss_total, 0) as loan_repayment_currency_loss_total,
  COALESCE(deposit_num, 0) as deposit_num,
  COALESCE(deposit_total, 0) as deposit_total,
  COALESCE(deposit_modification_num, 0) as deposit_modification_num,
  COALESCE(deposit_modification_total, 0) as deposit_modification_total,
  COALESCE(misc_num, 0) as misc_num,
  COALESCE(misc_total, 0) as misc_total,
  COALESCE(fundpool_repayment_num, 0) as fundpool_repayment_num,
  COALESCE(fundpool_repayment_total, 0) as fundpool_repayment_total,
  COALESCE(fundpool_match_num, 0) as fundpool_match_num,
  COALESCE(fundpool_match_total, 0) as fundpool_match_total,	
  COALESCE(kivapool_repayment_num, 0) as kivapool_repayment_num,
  COALESCE(kivapool_repayment_total, 0) as kivapool_repayment_total,
  COALESCE(kivapool_match_num, 0) as kivapool_match_num,
  COALESCE(kivapool_match_total, 0) as kivapool_match_total,
  COALESCE(promo_loan_credit_num, 0) as promo_loan_credit_num,
  COALESCE(promo_loan_credit_total, 0) as promo_loan_credit_total,
  COALESCE(promo_loan_reimbursement_num, 0) as promo_loan_reimbursement_num,
  COALESCE(promo_loan_reimbursement_total, 0) as promo_loan_reimbursement_total,
  COALESCE(cc_user_num, 0) as cc_user_num,
  COALESCE(cc_user_total, 0) as cc_user_total,
  COALESCE(uncategorized_num, 0) as uncategorized_num,
  COALESCE(uncategorized_total, 0) as uncategorized_total,
  COALESCE(loan_default_num, 0) as loan_default_num,
  COALESCE(loan_default_total, 0) as loan_default_total,
  COALESCE(withdrawal_sent_num, 0) as withdrawal_sent_num,
  COALESCE(withdrawal_sent_total, 0) as withdrawal_sent_total,
  COALESCE(promo_loan_default_num, 0) as promo_loan_default_num,
  COALESCE(promo_loan_default_total, 0) as promo_loan_default_total
  
  from vertex_fact_fund_account_credit_change_totals cct
  
  left join vertex_fact_fund_account_ledger_credit_change_totals lct on lct.fund_account_id = cct.fund_account_id