create or replace view vertex_fact_fund_account_credit_change_totals as

select fund_account_id,
               
  max(loan_purchase_num) as loan_purchase_num,
  max(loan_purchase_total) as loan_purchase_total,
  max(loan_purchase_modification_num) as loan_purchase_modification_first_day_id,
  max(loan_purchase_modification_total) as loan_purchase_modification_last_day_id,
  max(loan_purchase_auto_num) as loan_purchase_auto_num,
  max(loan_purchase_auto_total) as loan_purchase_auto_total,
  max(loan_expired_num) as loan_expired_num,
  max(loan_expired_total) as loan_expired_total,
  max(loan_expired_modification_num) as loan_expired_modification_num,
  max(loan_expired_modification_total) as loan_expired_modification_total,
  max(loan_refund_num) as loan_refund_num,
  max(loan_refund_total) as loan_refund_total,
  max(loan_refund_modification_num) as loan_refund_modification_num,
  max(loan_refund_modification_total) as loan_refund_modification_total,
  max(gift_purchase_num) as gift_purchase_num,
  max(gift_purchase_total) as gift_purchase_total,
  max(gift_purchase_modification_num) as gift_purchase_modification_num,
  max(gift_purchase_modification_total) as gift_purchase_modification_total,
  max(gift_redemption_num) as gift_redemption_num,
  max(gift_redemption_total) as gift_redemption_total,
  max(gift_expiration_num) as gift_expiration_num,
  max(gift_expiration_total) as gift_expiration_total,
  max(gift_expiration_modification_num) as gift_expiration_modification_num,
  max(gift_expiration_modification_total) as gift_expiration_modification_total,
  max(gift_expiration_donation_num) as gift_expiration_donation_num,
  max(gift_expiration_donation_total) as gift_expiration_donation_total,
  max(gift_expiration_donation_modification_num) as gift_expiration_donation_modification_num,
  max(gift_expiration_donation_modification_total) as gift_expiration_donation_modification_total,
  max(withdrawal_num) as withdrawal_num,
  max(withdrawal_total) as withdrawal_total,
  max(withdrawal_modification_num) as withdrawal_modification_num,
  max(withdrawal_modification_total) as withdrawal_modification_total,
  max(donation_num) as donation_num,
  max(donation_total) as donation_total,
  max(donation_modification_num) as donation_modification_num,
  max(donation_modification_total) as donation_modification_total,
  max(donation_auto_num) as donation_auto_num,
  max(donation_auto_total) as donation_auto_total,
  max(loan_repayment_num) as loan_repayment_num,
  max(loan_repayment_total) as loan_repayment_total,
  max(loan_repayment_currency_loss_num) as loan_repayment_currency_loss_num,
  max(loan_repayment_currency_loss_total) as loan_repayment_currency_loss_total,
  max(deposit_num) as deposit_num,
  max(deposit_total) as deposit_total,
  max(deposit_modification_num) as deposit_modification_num,
  max(deposit_modification_total) as deposit_modification_total,
  max(misc_num) as misc_num,
  max(misc_total) as misc_total,
  max(fundpool_repayment_num) as fundpool_repayment_num,
  max(fundpool_repayment_total) as fundpool_repayment_total,
  max(fundpool_match_num) as fundpool_match_num,
  max(fundpool_match_total) as fundpool_match_total,	
  max(kivapool_repayment_num) as kivapool_repayment_num,
  max(kivapool_repayment_total) as kivapool_repayment_total,
  max(kivapool_match_num) as kivapool_match_num,
  max(kivapool_match_total) as kivapool_match_total,
  max(promo_loan_credit_num) as promo_loan_credit_num,
  max(promo_loan_credit_total) as promo_loan_credit_total,
  max(promo_loan_reimbursement_num) as promo_loan_reimbursement_num,
  max(promo_loan_reimbursement_total) as promo_loan_reimbursement_total,
  max(cc_user_num) as cc_user_num,
  max(cc_user_total) as cc_user_total,
  max(uncategorized_num) as uncategorized_num,
  max(uncategorized_total) as uncategorized_total
  
  
 
from (  select fund_account_id, 
       
	case when type_name in ('loan_purchase') then COALESCE(count(1),0) end as loan_purchase_num,
	case when type_name in ('loan_purchase') then COALESCE(sum(cc.price),0) end as loan_purchase_total,
	case when type_name in ('m_loan_purchase_void','loan_share_recapture') then COALESCE(count(1),0) end as loan_purchase_modification_num,
        case when type_name in ('m_loan_purchase_void','loan_share_recapture') then COALESCE(sum(cc.price),0) end as loan_purchase_modification_total,
        case when type_name in ('loan_purchase_auto') then COALESCE(count(1),0) end as loan_purchase_auto_num,
	case when type_name in ('loan_purchase_auto') then COALESCE(sum(cc.price),0) end as loan_purchase_auto_total,
        case when type_name in ('loan_expired') then COALESCE(count(1),0) end as loan_expired_num,
	case when type_name in ('loan_expired') then COALESCE(sum(cc.price),0) end as loan_expired_total,
        case when type_name in ('loan_expired_modification') then COALESCE(count(1),0) end as loan_expired_modification_num,
	case when type_name in ('loan_expired_modification') then COALESCE(sum(cc.price),0) end as loan_expired_modification_total,
        case when type_name in ('loan_refund') then COALESCE(count(1),0) end as loan_refund_num,
	case when type_name in ('loan_refund') then COALESCE(sum(cc.price),0) end as loan_refund_total,
	case when type_name in ('m_loan_refund_reversal') then COALESCE(count(1),0) end as loan_refund_modification_num,
	case when type_name in ('m_loan_refund_reversal') then COALESCE(sum(cc.price),0) end as loan_refund_modification_total,
        case when type_name in ('gift_purchase') then COALESCE(count(1),0) end as gift_purchase_num,
	case when type_name in ('gift_purchase') then COALESCE(sum(cc.price),0) end as gift_purchase_total,
        case when type_name in ('gift_cancellation') then COALESCE(count(1),0) end as gift_purchase_modification_num,
	case when type_name in ('gift_cancellation') then COALESCE(sum(cc.price),0) end as gift_purchase_modification_total,
        case when type_name in ('gift_redemption') then COALESCE(count(1),0) end as gift_redemption_num,
	case when type_name in ('gift_redemption') then COALESCE(sum(cc.price),0) end as gift_redemption_total,
        case when type_name in ('gift_expiration') then COALESCE(count(1),0) end as gift_expiration_num,
	case when type_name in ('gift_expiration') then COALESCE(sum(cc.price),0) end as gift_expiration_total,
        case when type_name in ('gift_unexpiration') then COALESCE(count(1),0) end as gift_expiration_modification_num,
	case when type_name in ('gift_unexpiration') then COALESCE(sum(cc.price),0) end as gift_expiration_modification_total,
        case when type_name in ('gift_expiration_donation') then COALESCE(count(1),0) end as gift_expiration_donation_num,
	case when type_name in ('gift_expiration_donation') then COALESCE(sum(cc.price),0) end as gift_expiration_donation_total,
        case when type_name in ('gift_expiration_donation_refund') then COALESCE(count(1),0) end as gift_expiration_donation_modification_num,
	case when type_name in ('gift_expiration_donation_refund') then COALESCE(sum(cc.price),0) end as gift_expiration_donation_modification_total,
	case when type_name in ('withdrawal_request', 'm_withdrawal', 'm_check_withdrawal') then COALESCE(count(1),0) end as withdrawal_num,
	case when type_name in ('withdrawal_request', 'm_withdrawal', 'm_check_withdrawal') then COALESCE(sum(cc.price),0) end as withdrawal_total,
        case when type_name in ('withdrawal_modification', 'withdrawal_void', 'm_withdrawal_modification', 'withdrawal_returned', 'm_withdrawal_refund') then COALESCE(count(1),0) end as withdrawal_modification_num,
	case when type_name in ('withdrawal_modification', 'withdrawal_void', 'm_withdrawal_modification', 'withdrawal_returned', 'm_withdrawal_refund') then COALESCE(sum(cc.price),0) end as withdrawal_modification_total,
        case when type_name in ('donation', 'check_donation', 'm_donation', 'subscription_donation', 'fundpool_donation','contract_recovery', 'dedication_donation', 'inactive_credit_donation') then COALESCE(count(1),0) end as donation_num,
        case when type_name in ('donation', 'check_donation', 'm_donation', 'subscription_donation', 'fundpool_donation','contract_recovery', 'dedication_donation', 'inactive_credit_donation') then COALESCE(sum(cc.price),0) end as donation_total,
        case when type_name in ('donation_void', 'm_donation_void', 'subscription_donation_void', 'dedication_donation_void', 'check_donation_void', 'inactive_donation_void') then COALESCE(count(1),0) end as donation_modification_num,
        case when type_name in ('donation_void', 'm_donation_void', 'subscription_donation_void', 'dedication_donation_void', 'check_donation_void', 'inactive_donation_void') then COALESCE(sum(cc.price),0) end as donation_modification_total,
        case when type_name in ('autolend_donation', 'autolend_donation_void', 'loan_matcher_donation', 'loan_matcher_donation_void') then COALESCE(count(1),0) end as donation_auto_num,
        case when type_name in ('autolend_donation', 'autolend_donation_void', 'loan_matcher_donation', 'loan_matcher_donation_void') then COALESCE(sum(cc.price),0) end as donation_auto_total,
        case when type_name in ('loan_repayment') then COALESCE(count(1),0) end as loan_repayment_num,
	case when type_name in ('loan_repayment') then COALESCE(sum(cc.price),0) end as loan_repayment_total,
        case when type_name in ('loan_repayment_currency_loss', 'loan_repayment_currency_credit') then COALESCE(count(1),0) end as loan_repayment_currency_loss_num,
	case when type_name in ('loan_repayment_currency_loss', 'loan_repayment_currency_credit') then COALESCE(sum(cc.price),0) end as loan_repayment_currency_loss_total,
        case when type_name in ('deposit', 'check_deposit_9034', 'm_deposit', 'm_check_deposit', 'm_wire_transfer_deposit', 'echeck_deposit', 'fundpool_funding', 'kivapool_funding') then COALESCE(count(1),0) end as deposit_num,
	case when type_name in ('deposit', 'check_deposit_9034', 'm_deposit', 'm_check_deposit', 'm_wire_transfer_deposit', 'echeck_deposit', 'fundpool_funding', 'kivapool_funding') then COALESCE(sum(cc.price),0) end as deposit_total,
        case when type_name in ('deposit_refund', 'm_check_deposit_void', 'm_check_deposit_currency_fix', 'deposit_modification', 'm_check_deposit_currency_gain',
			'm_check_deposit_currency_loss', 'deposit_reversal', 'echeck_failed', 'fundpool_funding_void', 'kivapool_funding_void') then COALESCE(count(1),0) end as deposit_modification_num,
	case when type_name in ('deposit_refund', 'm_check_deposit_void', 'm_check_deposit_currency_fix', 'deposit_modification', 'm_check_deposit_currency_gain',
			'm_check_deposit_currency_loss', 'deposit_reversal', 'echeck_failed', 'fundpool_funding_void', 'kivapool_funding_void') then COALESCE(sum(cc.price),0) end as deposit_modification_total,
        case when type_name in ('m_credit', 'm_debit', 'm_credit_from_ops', 'm_credit_transfer', 'initial_balance') then COALESCE(count(1),0) end as misc_num,
	case when type_name in ('m_credit', 'm_debit', 'm_credit_from_ops', 'm_credit_transfer', 'initial_balance') then COALESCE(sum(cc.price),0) end as misc_total,
        case when type_name in ('fundpool_repayment') then COALESCE(count(1),0) end as fundpool_repayment_num,
	case when type_name in ('fundpool_repayment') then COALESCE(sum(cc.price),0) end as fundpool_repayment_total,
	case when type_name in ('fundpool_match') then COALESCE(count(1),0) end as fundpool_match_num,
	case when type_name in ('fundpool_match') then COALESCE(sum(cc.price),0) end as fundpool_match_total,	
	case when type_name in ('kivapool_repayment') then COALESCE(count(1),0) end as kivapool_repayment_num,
	case when type_name in ('kivapool_repayment') then COALESCE(sum(cc.price),0) end as kivapool_repayment_total,
	case when type_name in ('kivapool_match') then COALESCE(count(1),0) end as kivapool_match_num,
	case when type_name in ('kivapool_match') then COALESCE(sum(cc.price),0) end as kivapool_match_total,
	case when type_name in ('promo_loan_credit') then COALESCE(count(1),0) end as promo_loan_credit_num,
	case when type_name in ('promo_loan_credit') then COALESCE(sum(cc.price),0) end as promo_loan_credit_total,
	case when type_name in ('promo_loan_reimbursement') then COALESCE(count(1),0) end as promo_loan_reimbursement_num,
	case when type_name in ('promo_loan_reimbursement') then COALESCE(sum(cc.price),0) end as promo_loan_reimbursement_total,
	
	--cc_user_day_id pulls from loan_purchase, gift_purchase, gift_redemption, withdrawal, donation, deposit
	case when type_name in ('loan_purchase', 'gift_purchase', 'gift_redemption','withdrawal_request', 'm_withdrawal', 'm_check_withdrawal','donation', 'check_donation', 'm_donation', 'subscription_donation', 'fundpool_donation','contract_recovery', 'dedication_donation', 'inactive_credit_donation',
	               'deposit', 'check_deposit_9034', 'm_deposit', 'm_check_deposit', 'm_wire_transfer_deposit', 'echeck_deposit', 'fundpool_funding', 'kivapool_funding') then COALESCE(count(1),0) end as cc_user_num,
	case when type_name in ('loan_purchase', 'gift_purchase', 'gift_redemption','withdrawal_request', 'm_withdrawal', 'm_check_withdrawal','donation', 'check_donation', 'm_donation', 'subscription_donation', 'fundpool_donation','contract_recovery', 'dedication_donation', 'inactive_credit_donation',
	               'deposit', 'check_deposit_9034', 'm_deposit', 'm_check_deposit', 'm_wire_transfer_deposit', 'echeck_deposit', 'fundpool_funding', 'kivapool_funding') then COALESCE(sum(cc.price),0) end as cc_user_total,
	               
	-- uncategorized not in any of above
	case when type_name not in ('loan_purchase','m_loan_purchase_void','loan_share_recapture','loan_purchase_auto','loan_expired','loan_expired_modification','loan_refund','m_loan_refund_reversal',
                'gift_purchase','gift_cancellation','gift_redemption','gift_expiration','gift_unexpiration','gift_expiration_donation','gift_expiration_donation_refund',
                'withdrawal_request', 'm_withdrawal', 'm_check_withdrawal','withdrawal_modification', 'withdrawal_void', 'm_withdrawal_modification', 'withdrawal_returned', 'm_withdrawal_refund','donation', 'check_donation', 'm_donation', 'subscription_donation', 'fundpool_donation','contract_recovery', 'dedication_donation', 'inactive_credit_donation',
                'donation_void', 'm_donation_void', 'subscription_donation_void', 'dedication_donation_void', 'check_donation_void', 'inactive_donation_void','autolend_donation', 'autolend_donation_void', 'loan_matcher_donation', 'loan_matcher_donation_void',
                'loan_repayment','loan_repayment_currency_loss', 'loan_repayment_currency_credit','deposit', 'check_deposit_9034', 'm_deposit', 'm_check_deposit', 'm_wire_transfer_deposit', 'echeck_deposit', 'fundpool_funding', 'kivapool_funding',
                'deposit_refund', 'm_check_deposit_void', 'm_check_deposit_currency_fix', 'deposit_modification', 'm_check_deposit_currency_gain',
                'm_check_deposit_currency_loss', 'deposit_reversal', 'echeck_failed', 'fundpool_funding_void', 'kivapool_funding_void',
                'm_credit', 'm_debit', 'm_credit_from_ops', 'm_credit_transfer', 'initial_balance','fundpool_repayment','fundpool_match','kivapool_repayment','kivapool_match','promo_loan_credit','promo_loan_reimbursement')	
                then COALESCE(count(1),0) end as uncategorized_num,
        case when type_name not in ('loan_purchase','m_loan_purchase_void','loan_share_recapture','loan_purchase_auto','loan_expired','loan_expired_modification','loan_refund','m_loan_refund_reversal',
                'gift_purchase','gift_cancellation','gift_redemption','gift_expiration','gift_unexpiration','gift_expiration_donation','gift_expiration_donation_refund',
                'withdrawal_request', 'm_withdrawal', 'm_check_withdrawal','withdrawal_modification', 'withdrawal_void', 'm_withdrawal_modification', 'withdrawal_returned', 'm_withdrawal_refund','donation', 'check_donation', 'm_donation', 'subscription_donation', 'fundpool_donation','contract_recovery', 'dedication_donation', 'inactive_credit_donation',
                'donation_void', 'm_donation_void', 'subscription_donation_void', 'dedication_donation_void', 'check_donation_void', 'inactive_donation_void','autolend_donation', 'autolend_donation_void', 'loan_matcher_donation', 'loan_matcher_donation_void',
                'loan_repayment','loan_repayment_currency_loss', 'loan_repayment_currency_credit','deposit', 'check_deposit_9034', 'm_deposit', 'm_check_deposit', 'm_wire_transfer_deposit', 'echeck_deposit', 'fundpool_funding', 'kivapool_funding',
                'deposit_refund', 'm_check_deposit_void', 'm_check_deposit_currency_fix', 'deposit_modification', 'm_check_deposit_currency_gain',
                'm_check_deposit_currency_loss', 'deposit_reversal', 'echeck_failed', 'fundpool_funding_void', 'kivapool_funding_void',
                'm_credit', 'm_debit', 'm_credit_from_ops', 'm_credit_transfer', 'initial_balance','fundpool_repayment','fundpool_match','kivapool_repayment','kivapool_match','promo_loan_credit','promo_loan_reimbursement')	        
                then COALESCE(sum(cc.price),0) end as uncategorized_total
                
        from vertex_fact_credit_change cc
        inner join vertex_dim_credit_change_type cct on cc.dim_credit_change_type_id = cct.id
        where cct.source_table_name = 'credit_change' 
        
        group by fund_account_id, type_name
     
     ) totals
        
     
group by totals.fund_account_id;