create or replace view vertex_fact_fund_account as

select cct.fund_account_id,
               
  loan_purchase_num,
  loan_purchase_total,
  loan_purchase_modification_first_day_id,
  loan_purchase_modification_last_day_id,
  loan_purchase_auto_num,
  loan_purchase_auto_total,
  loan_expired_num,
  loan_expired_total,
  loan_expired_modification_num,
  loan_expired_modification_total,
  loan_refund_num,
  loan_refund_total,
  loan_refund_modification_num,
  loan_refund_modification_total,
  gift_purchase_num,
  gift_purchase_total,
  gift_purchase_modification_num,
  gift_purchase_modification_total,
  gift_redemption_num,
  gift_redemption_total,
  gift_expiration_num,
  gift_expiration_total,
  gift_expiration_modification_num,
  gift_expiration_modification_total,
  gift_expiration_donation_num,
  gift_expiration_donation_total,
  gift_expiration_donation_modification_num,
  gift_expiration_donation_modification_total,
  withdrawal_num,
  withdrawal_total,
  withdrawal_modification_num,
  withdrawal_modification_total,
  donation_num,
  donation_total,
  donation_modification_num,
  donation_modification_total,
  donation_auto_num,
  donation_auto_total,
  loan_repayment_num,
  loan_repayment_total,
  loan_repayment_currency_loss_num,
  loan_repayment_currency_loss_total,
  deposit_num,
  deposit_total,
  deposit_modification_num,
  deposit_modification_total,
  misc_num,
  misc_total,
  fundpool_repayment_num,
  fundpool_repayment_total,
  fundpool_match_num,
  fundpool_match_total,	
  kivapool_repayment_num,
  kivapool_repayment_total,
  kivapool_match_num,
  kivapool_match_total,
  promo_loan_credit_num,
  promo_loan_credit_total,
  promo_loan_reimbursement_num,
  promo_loan_reimbursement_total,
  cc_user_num,
  cc_user_total,
  uncategorized_num,
  uncategorized_total,
  loan_default_num,
  loan_default_total,
  withdrawal_sent_num,
  withdrawal_sent_total,
  promo_loan_default_num,
  promo_loan_default_total
  
  from vertex_fact_fund_account_credit_change_totals cct
  
  left join vertex_fact_fund_account_ledger_credit_change_totals lct on lct.fund_account_id = cct.fund_account_id