DROP TABLE IF EXISTS vertex_credit_change_group;
CREATE TABLE vertex_credit_change_group (id Integer NOT NULL, name Varchar(50) NOT NULL, PRIMARY KEY (id));
INSERT INTO vertex_credit_change_group (id, name) VALUES (1, 'loan_purchase');
INSERT INTO vertex_credit_change_group (id, name) VALUES (2, 'loan_expiration');
INSERT INTO vertex_credit_change_group (id, name) VALUES (3, 'loan_refund');
INSERT INTO vertex_credit_change_group (id, name) VALUES (4, 'gift_expiration');
INSERT INTO vertex_credit_change_group (id, name) VALUES (5, 'gift_purchase');
INSERT INTO vertex_credit_change_group (id, name) VALUES (6, 'gift_expiration_donation');
INSERT INTO vertex_credit_change_group (id, name) VALUES (7, 'donation');
INSERT INTO vertex_credit_change_group (id, name) VALUES (8, 'loan_repayment');
INSERT INTO vertex_credit_change_group (id, name) VALUES (9, 'currency_loss');
INSERT INTO vertex_credit_change_group (id, name) VALUES (10, 'deposit');
INSERT INTO vertex_credit_change_group (id, name) VALUES (11, 'fundpool');
INSERT INTO vertex_credit_change_group (id, name) VALUES (12, 'kivapool');
INSERT INTO vertex_credit_change_group (id, name) VALUES (13, 'promo_card');
INSERT INTO vertex_credit_change_group (id, name) VALUES (14, 'withdrawal');
INSERT INTO vertex_credit_change_group (id, name) VALUES (15, 'gift_redemption');
INSERT INTO vertex_credit_change_group (id, name) VALUES (16, 'ops_credit');
INSERT INTO vertex_credit_change_group (id, name) VALUES (17, 'credit_transfer');
INSERT INTO vertex_credit_change_group (id, name) VALUES (18, 'zip_transfer');
INSERT INTO vertex_credit_change_group (id, name) VALUES (19, 'partner_not_cash');
INSERT INTO vertex_credit_change_group (id, name) VALUES (20, 'operations_misc');
INSERT INTO vertex_credit_change_group (id, name) VALUES (21, 'ledger_misc');
INSERT INTO vertex_credit_change_group (id, name) VALUES (22, 'loan_default');
INSERT INTO vertex_credit_change_group (id, name) VALUES (23, 'escheatment');
INSERT INTO vertex_credit_change_group (id, name) VALUES (24, 'gift_breakage');
INSERT INTO vertex_credit_change_group (id, name) VALUES (25, 'bank_transfer');
INSERT INTO vertex_credit_change_group (id, name) VALUES (26, 'bank_fees');
INSERT INTO vertex_credit_change_group (id, name) VALUES (27, 'interest');
INSERT INTO vertex_credit_change_group (id, name) VALUES (28, 'operations_transfer');
INSERT INTO vertex_credit_change_group (id, name) VALUES (29, 'partner_collected');
INSERT INTO vertex_credit_change_group (id, name) VALUES (30, 'partner_currency_credit');
INSERT INTO vertex_credit_change_group (id, name) VALUES (31, 'partner_paid');
INSERT INTO vertex_credit_change_group (id, name) VALUES (32, 'partner_ops_adjust');

--grant select on table verse_prod.vertex_credit_change_group to verse_prod_read_only_role;