create or replace view vertex_dim_fund_account_first_day_ids as

select fund_account_id, 
  NULL::INT as create_time,
  NULL::INT create_day_id,
  NULL as inactive_credit_recipient,
  NULL as donate_on_repayment,
  NULL::INT country_id,
  NULL::INT contact_info_id,
  NULL::INT geo_state_codes_id,
  min(case when reporting_group = 'loan_purchase' and is_modification = 'false' then min_effective_day_id end) as loan_purchase_first_day_id,
  min(case when reporting_group = 'loan_purchase' and is_modification = 'false' then max_effective_day_id end) as loan_purchase_last_day_id,
  min(case when reporting_group = 'loan_purchase' and is_modification = 'true' then min_effective_day_id end) as loan_purchase_modification_first_day_id,
  min(case when reporting_group = 'loan_purchase' and is_modification = 'true' then max_effective_day_id end) as loan_purchase_modification_last_day_id,
  NULL::INT as loan_purchase_auto_first_day_id,
  NULL::INT as loan_purchase_auto_last_day_id,
  NULL::INT as loan_expired_first_day_id,
  NULL::INT as loan_expired_last_day_id,
  NULL::INT as loan_expired_modification_first_day_id,
  NULL::INT as loan_expired_modification_last_day_id,
  NULL::INT as loan_refund_first_day_id,
  NULL::INT as loan_refund_last_day_id,
  NULL::INT as loan_refund_modification_first_day_id,
  NULL::INT as loan_refund_modification_last_day_id,
  NULL::INT as gift_purchase_first_day_id,
  NULL::INT as gift_purchase_last_day_id,
  NULL::INT as gift_purchase_modification_first_day_id,
  NULL::INT as gift_purchase_modification_last_day_id,
  NULL::INT as gift_redemption_first_day_id,
  NULL::INT as gift_redemption_last_day_id,
  NULL::INT as gift_expiration_first_day_id,
  NULL::INT as gift_expiration_last_day_id,
  NULL::INT as gift_expiration_modification_first_day_id,
  NULL::INT as gift_expiration_modification_last_day_id,
  NULL::INT as gift_expiration_donation_first_day_id,
  NULL::INT as gift_expiration_donation_last_day_id,
  NULL::INT as gift_expiration_donation_modification_first_day_id,
  NULL::INT as gift_expiration_donation_modification_last_day_id,
  NULL::INT as donation_first_day_id,
  NULL::INT as donation_last_day_id,
  NULL::INT as donation_first_modification_day_id,
  NULL::INT as donation_last_modification_day_id,
  NULL::INT as donation_auto_first_day_id,
  NULL::INT as donation_auto_last_day_id,
  NULL::INT as withdrawal_first_day_id,
  NULL::INT as withdrawal_last_day_id,
  NULL::INT as withdrawal_modification_first_day_id,
  NULL::INT as withdrawal_modification_last_day_id,
  NULL::INT as loan_repayment_first_day_id,
  NULL::INT as loan_repayment_last_day_id,
  NULL::INT as loan_repayment_modification_first_day_id,
  NULL::INT as loan_repayment_modification_last_day_id,
  NULL::INT as loan_repayment_currency_loss_first_day_id,
  NULL::INT as loan_repayment_currency_loss_last_day_id,
  NULL::INT as deposit_first_day_id,
  NULL::INT as deposit_last_day_id,
  NULL::INT as deposit_modification_first_day_id,
  NULL::INT as deposit_modification_last_day_id,
  NULL::INT as misc_first_day_id,
  NULL::INT as misc_last_day_id,
  NULL::INT as cc_all_first_day_id,
  NULL::INT as cc_all_last_day_id,
  NULL::INT as cc_user_first_day_id,
  NULL::INT as cc_user_last_day_id,
  NULL::INT as fundpool_repayment_first_day_id,
  NULL::INT as fundpool_repayment_last_day_id,
  NULL::INT as fundpool_match_first_day_id,
  NULL::INT as fundpool_match_last_day_id,
  NULL::INT as kivapool_repayment_first_day_id,
  NULL::INT as kivapool_repayment_last_day_id,
  NULL::INT as kivapool_match_first_day_id,
  NULL::INT as kivapool_match_last_day_id,
  NULL::INT as promo_loan_credit_first_day_id,
  NULL::INT as promo_loan_credit_last_day_id,
  NULL::INT as promo_loan_reimbursement_first_day_id,
  NULL::INT as promo_loan_reimbursement_last_day_id,
  NULL::INT as uncategorized_first_day_id,
  NULL::INT as uncateogorized_last_day_id,
  NULL::INT as loan_default_first_day_id,
  NULL::INT as loan_default_last_day_id,
  NULL::INT as withdrawal_sent_first_day_id,
  NULL::INT as withdrawal_sent_last_day_id,
  NULL::INT as promo_loan_default_first_day_id,
  NULL::INT as promo_loan_default_last_day_id
  
        
  
from (        
        select fund_account_id, cct.reporting_group, cct.is_modification,
        min(effective_day_id) as min_effective_day_id,
        max(effective_day_id) as max_effective_day_id
        from vertex_fact_credit_change cc
        inner join vertex_dim_credit_change_type cct on cc.dim_credit_change_type_id = cct.id
        where cct.source_table_name = 'credit_change' 
        group by cc.fund_account_id, cct.reporting_group, cct.is_modification 
     ) day_ids

group by day_ids.fund_account_id;