create or replace view vertex_dim_fund_account as

select faa.owner_login_id,
	faa.fund_account_id,
	faa.fund_account_type_id,
	faa.user_account_type_id, -- The user_account_type_id is selected again for naming convention, to help with dimension column. This actually higlight poor name in KIVA db as well. user_account_type should really be user_account_type_id
	faa.user_account_type,
	faa.source_of_funds,
	faa.accounting_category,
	faa.accounting_category_id,
	faa.is_default_account,
	faa.create_time,
	faa.donate_on_repayment,
	faa.current_balance,
	faa.is_closed,
	faa.is_withdrawable,
	faa.inactive_credit_recipient,
	faa.contact_info_id, -- for dimension column
	faa.billing_contact_id, -- For intermediate column - just for easy debugging
	faa.country_id,
	faa.geo_state_codes_id,
	faa.current_portfolio_num,
	faa.current_portfolio_total,
	faa.e_current_portfolio_outstanding,
	faa.e_current_portfolio_repaid,
	fid.fundpool_match_first_item_id,
	fid.kivapool_match_first_item_id,
	fdd.loan_purchase_first_day_id,
        fdd.loan_purchase_last_day_id,
        fdd.loan_purchase_modification_first_day_id,
        fdd.loan_purchase_modification_last_day_id,
        fdd.loan_purchase_auto_first_day_id,
        fdd.loan_purchase_auto_last_day_id,
        fdd.loan_expired_first_day_id,
        fdd.loan_expired_last_day_id,
        fdd.loan_expired_modification_first_day_id,
        fdd.loan_expired_modification_last_day_id,
        fdd.loan_refund_first_day_id,
        fdd.loan_refund_last_day_id,
        fdd.loan_refund_modification_first_day_id,
        fdd.loan_refund_modification_last_day_id,
        fdd.gift_purchase_first_day_id,
        fdd.gift_purchase_last_day_id,
        fdd.gift_purchase_modification_first_day_id,
        fdd.gift_purchase_modification_last_day_id,
        fdd.gift_redemption_first_day_id,
        fdd.gift_redemption_last_day_id,
        fdd.gift_expiration_first_day_id,
        fdd.gift_expiration_last_day_id,
        fdd.gift_expiration_modification_first_day_id,
        fdd.gift_expiration_modification_last_day_id,
        fdd.gift_expiration_donation_first_day_id,
        fdd.gift_expiration_donation_last_day_id,
        fdd.gift_expiration_donation_modification_first_day_id,
        fdd.gift_expiration_donation_modification_last_day_id,
        fdd.donation_first_day_id,
        fdd.donation_last_day_id,
        fdd.donation_first_modification_day_id,
        fdd.donation_last_modification_day_id,
        fdd.donation_auto_first_day_id,
        fdd.donation_auto_last_day_id,
        fdd.withdrawal_first_day_id,
        fdd.withdrawal_last_day_id,
        fdd.withdrawal_modification_first_day_id,
        fdd.withdrawal_modification_last_day_id,
        fdd.loan_repayment_first_day_id,
        fdd.loan_repayment_last_day_id,
        fdd.loan_repayment_currency_loss_first_day_id,
        fdd.loan_repayment_currency_loss_last_day_id,
        fdd.deposit_first_day_id,
        fdd.deposit_last_day_id,
        fdd.deposit_modification_first_day_id,
        fdd.deposit_modification_last_day_id,
        fdd.misc_first_day_id,
        fdd.misc_last_day_id,
        fdd.cc_all_first_day_id,
        fdd.cc_all_last_day_id,
        fdd.cc_user_first_day_id,
        fdd.cc_user_last_day_id,
        fdd.fundpool_repayment_first_day_id,
        fdd.fundpool_repayment_last_day_id,
        fdd.fundpool_match_first_day_id,
        fdd.fundpool_match_last_day_id,
        fdd.kivapool_repayment_first_day_id,
        fdd.kivapool_repayment_last_day_id,
        fdd.kivapool_match_first_day_id,
        fdd.kivapool_match_last_day_id,
        fdd.promo_loan_credit_first_day_id,
        fdd.promo_loan_credit_last_day_id,
        fdd.promo_loan_reimbursement_first_day_id,
        fdd.promo_loan_reimbursement_last_day_id,
        fdd.uncategorized_first_day_id,
        fdd.uncateogorized_last_day_id,
        ldd.loan_default_first_day_id,
        ldd.loan_default_last_day_id,
        ldd.withdrawal_sent_first_day_id,
        ldd.withdrawal_sent_last_day_id,
        ldd.promo_loan_default_first_day_id,
        ldd.promo_loan_default_last_day_id
  

from vertex_dim_fund_account_accounts faa

left join vertex_dim_fund_account_first_item_ids fid on fid.fund_account_id = faa.fund_account_id

left join vertex_dim_fund_account_first_day_ids fdd on fdd.fund_account_id = faa.fund_account_id

left join vertex_dim_fund_account_ledger_first_day_ids ldd on ldd.fund_account_id = faa.fund_account_id;
