--create user van identified by 'pwd';
--create user mike identified by 'pwd';
--create user nikkiw identified by 'pwd';
--create user vertex identified by 'pwd';
--create user verse identified by 'pwd';
--create user sam identified by 'pwd';
--create user looker identified by 'pwd';
--create user bamboo identified by 'pwd';
--create user dthomas identified by 'pwd';
--create user jake identified by 'pwd';
--create user zahid identified by 'pwd';
--create user amy identified by 'pwd';
--create user devpush identified by 'pwd';


grant authentication host_pass to mike;
grant authentication local_pass to mike;
grant authentication host_pass to van;
grant authentication local_pass to van;
grant authentication host_pass to nikkiw;
grant authentication local_pass to nikkiw;
grant authentication host_pass to vertex;
grant authentication local_pass to vertex;
grant authentication host_pass to verse;
grant authentication local_pass to verse;
grant authentication host_pass to sam;
grant authentication local_pass to sam;
grant authentication host_pass to looker;
grant authentication local_pass to looker;
grant authentication host_pass to bamboo;
grant authentication local_pass to bamboo;
grant authentication host_pass to dthomas;
grant authentication local_pass to dthomas;
grant authentication host_pass to jake;
grant authentication local_pass to jake;
grant authentication host_pass to zahid;
grant authentication local_pass to zahid;
grant authentication host_pass to amy;
grant authentication local_pass to amy;
grant authentication host_pass to devpush;
grant authentication local_pass to devpush;

alter user vertex search_path "$user", ods_kiva, verse, public;
alter user mike search_path "$user", ods_kiva, verse, public;
alter user van search_path "$user", ods_kiva, verse, public;
alter user nikkiw search_path "$user", ods_kiva, verse, public;
alter user looker search_path "$user", vertex, ods_kiva, verse, public;
alter user bamboo search_path "$user", ods_kiva, verse, public;
alter user dthomas search_path "$user", ods_kiva, verse, public;
alter user jake search_path "$user", ods_kiva, verse, public;
alter user zahid search_path "$user", ods_kiva, verse, public;
alter user amy search_path "$user", ods_kiva, verse, public;
alter user devpush search_path "$user", ods_kiva, verse, public; -- change $user to vertex when ready
